using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FactoryPattern
{
    class KeyByGen : IKey
    {
        public string GetKey()
        {
            return "Key generated by keygen";
        }
    }
}
